export const CUSTOM_IP_ADDRESS_SETTINGS_KEY = 'custom_ip_address';
export const CUSTOM_IP_ADDRESS_PAIR_KEY = 'custom_ip_address';
export const LIST_DEVICES_PAIR_KEY = 'list_devices';
export const MEASURE_TEMPERATURE_CAPABILITY = 'measure_temperature';
export const MEASURE_TEMPERATURE_MANIFOLD_HEAD_CAPABILITY = 'measure_temperature.manifold_head';
export const MEASURE_TEMPERATURE_FLOOR_CAPABILITY = 'measure_temperature.floor';
export const MEASURE_TEMPERATURE_FLOOR_MIN_CAPABILITY = 'measure_temperature.floor_min_setpoint';
export const MEASURE_TEMPERATURE_FLOOR_MAX_CAPABILITY = 'measure_temperature.floor_max_setpoint';
export const TARGET_TEMPERATURE_CAPABILITY = 'target_temperature';
export const MEASURE_HUMIDITY_CAPABILITY = 'measure_humidity';
export const IS_HEATING_CAPABILITY = 'is_heating';
export const BYPASS_ENABLED_CAPABILITY = 'bypass_enabled';
export const ECO_MODE_CAPABILITY = 'eco_mode';
export const THERMOSTAT_MODE_CAPABILITY = 'thermostat_mode';
export const VALVE_POS_PERCENT_CAPABILITY = 'valve_pos_percent';
export const ALARM_BATTERY_CAPABILITY = 'alarm_battery';
export const ALARM_TAMPER_CAPABILITY = 'alarm_tamper';
export const ALARM_AIR_SENSOR_CAPABILITY = 'alarm_generic.air_sensor';
export const ALARM_EXT_SENSOR_CAPABILITY = 'alarm_generic.ext_sensor';
export const ALARM_RH_SENSOR_CAPABILITY = 'alarm_generic.rh_sensor';
export const ALARM_RF_ERROR_CAPABILITY = 'alarm_generic.rf_error';
export const ALARM_RF_LOW_SIG_CAPABILITY = 'alarm_generic.rf_low_sig';
export const ALARM_VALVE_POS_CAPABILITY = 'alarm_generic.valve_pos';
export const ALARM_HEAT_FALLBACK_CAPABILITY = 'alarm_generic.heat_fallback';
export const ALARM_FLOOR_LIMIT_CAPABILITY = 'alarm_generic.floor_limit';
export const ALARM_GENERAL_SYSTEM_CAPABILITY = 'alarm_generic.system';
export const SYS_SUPPLY_DIAGNOSTIC_CAPABILITY = 'sys_supply_diagnostic';
export const POLL_INTERVAL_MS = 1000 * 60 * 1; // 1 minute
export const INIT_TIMEOUT_MS = 1000 * 2; // 2 seconds
export const CACHE_EXPIRATION_MS = 60000; // 60 seconds
export const FETCH_TIMEOUT_MS = 10000; // 10 seconds
