export const CUSTOM_IP_ADDRESS_SETTINGS_KEY = 'custom_ip_address';
export const DEBUG_DEVICES_SETTINGS_KEY = 'debug_devices';
export const CUSTOM_IP_ADDRESS_PAIR_KEY = 'custom_ip_address';
export const LIST_DEVICES_PAIR_KEY = 'list_devices';
export const MEASURE_TEMPERATURE_CAPABILITY = 'measure_temperature';
export const TARGET_TEMPERATURE_CAPABILITY = 'target_temperature';
export const MEASURE_HUMIDITY_CAPABILITY = 'measure_humidity';
export const ALARM_BATTERY_CAPABILITY = 'alarm_battery';
export const ALARM_TAMPER_CAPABILITY = 'alarm_tamper';
export const ALARM_AIR_SENSOR_CAPABILITY = 'alarm_generic.air_sensor';
export const ALARM_EXT_SENSOR_CAPABILITY = 'alarm_generic.ext_sensor';
export const ALARM_RH_SENSOR_CAPABILITY = 'alarm_generic.rh_sensor';
export const ALARM_RF_ERROR_CAPABILITY = 'alarm_generic.rf_error';
export const ALARM_RF_LOW_SIG_CAPABILITY = 'alarm_generic.rf_low_sig';
export const ALARM_VALVE_POS_CAPABILITY = 'alarm_generic.valve_pos';
export const ALARM_HEAT_FALLBACK_CAPABILITY = 'alarm_generic.heat_fallback';
export const POLL_INTERVAL_MS = 1000 * 60 * 1; // 1 minute
export const INIT_TIMEOUT_MS = 1000 * 2; // 2 seconds
export const CACHE_EXPIRATION_MS = 60000; // 60 seconds
export const FETCH_TIMEOUT_MS = 10000; // 10 seconds
