name: Validate Homey App
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  main:
    name: Validate Homey App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - uses: athombv/github-action-homey-app-validate@master
        with:
          level: verified
